-- ตารางหลัก ERP (ย้ายจาก MySQL / db_mns) สำหรับ Neon PostgreSQL
-- ข้อมูลเดิม: import จาก dump แยกหรือสคริปต์ — ที่นี่มีเฉพาะโครง + seed ตารางอ้างอิง

CREATE TABLE "customer" (
    "cus_id" SERIAL NOT NULL,
    "cus_code" VARCHAR(11) NOT NULL,
    "cus_name" VARCHAR(300) NOT NULL,
    "cus_address" TEXT NOT NULL DEFAULT '',
    "cus_umpher" VARCHAR(200) NOT NULL DEFAULT '',
    "cus_province" INTEGER NOT NULL DEFAULT 0,
    "cus_zipcode" VARCHAR(7) NOT NULL DEFAULT '',
    "cus_tel" VARCHAR(20) NOT NULL DEFAULT '',
    "cus_fax" VARCHAR(20) NOT NULL DEFAULT '',
    "cus_tax" VARCHAR(20) NOT NULL DEFAULT '',
    "cus_contact" VARCHAR(300) NOT NULL DEFAULT '',
    "contact_tel" VARCHAR(20) NOT NULL DEFAULT '',
    "contact_email" VARCHAR(300) NOT NULL DEFAULT '',
    "cus_info" TEXT NOT NULL DEFAULT '',
    "public" INTEGER NOT NULL DEFAULT 1,
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "customer_pkey" PRIMARY KEY ("cus_id")
);

CREATE TABLE "workstatus" (
    "ws_id" INTEGER NOT NULL,
    "ws_name" VARCHAR(200) NOT NULL,
    "info" TEXT NOT NULL DEFAULT '',
    "list" SMALLINT NOT NULL DEFAULT 0,
    "public" INTEGER NOT NULL DEFAULT 1,
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "workstatus_pkey" PRIMARY KEY ("ws_id")
);

CREATE TABLE "workgroup" (
    "wg_id" INTEGER NOT NULL,
    "wg_name" VARCHAR(200) NOT NULL,
    "info" TEXT NOT NULL DEFAULT '',
    "list" SMALLINT NOT NULL DEFAULT 0,
    "public" INTEGER NOT NULL DEFAULT 1,
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "workgroup_pkey" PRIMARY KEY ("wg_id")
);

CREATE TABLE "user_group" (
    "group_id" INTEGER NOT NULL,
    "group_tid" INTEGER NOT NULL DEFAULT 0,
    "group_name" VARCHAR(200) NOT NULL,
    "file" VARCHAR(100) NOT NULL DEFAULT '',
    "info" VARCHAR(200) NOT NULL DEFAULT '',
    "admin" INTEGER NOT NULL DEFAULT 0,
    "public" INTEGER NOT NULL DEFAULT 1,
    "datetime" VARCHAR(100) NOT NULL DEFAULT '',
    CONSTRAINT "user_group_pkey" PRIMARY KEY ("group_id")
);

CREATE TABLE "user_data" (
    "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_gid" INTEGER NOT NULL DEFAULT 1,
    "admin" INTEGER NOT NULL DEFAULT 0,
    "fname" VARCHAR(200) NOT NULL DEFAULT '',
    "lname" VARCHAR(100) NOT NULL DEFAULT '',
    "bday" DATE NOT NULL DEFAULT '1970-01-01',
    "sex" VARCHAR(10) NOT NULL DEFAULT '',
    "position" VARCHAR(200) NOT NULL DEFAULT '',
    "address" VARCHAR(150) NOT NULL DEFAULT '',
    "umpher" VARCHAR(50) NOT NULL DEFAULT '',
    "province" SMALLINT NOT NULL DEFAULT 0,
    "zipcode" VARCHAR(5) NOT NULL DEFAULT '',
    "phonenumber" VARCHAR(15) NOT NULL DEFAULT '',
    "email" VARCHAR(100) NOT NULL DEFAULT '',
    "signup" VARCHAR(100) NOT NULL DEFAULT '',
    "username" VARCHAR(30) NOT NULL,
    "password" VARCHAR(30) NOT NULL DEFAULT '',
    "loginstatus" INTEGER NOT NULL DEFAULT 0,
    "lastupdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastlogin" VARCHAR(100) NOT NULL DEFAULT '',
    "user_ip" VARCHAR(15) NOT NULL DEFAULT '',
    "file" VARCHAR(100) NOT NULL DEFAULT '',
    "list" INTEGER NOT NULL DEFAULT 0,
    "public" INTEGER NOT NULL DEFAULT 1,
    "admin_id" INTEGER NOT NULL DEFAULT 0,
    "nickname" VARCHAR(200) NOT NULL DEFAULT '',
    "employment_status" VARCHAR(100) NOT NULL DEFAULT '',
    "company_display" VARCHAR(300) NOT NULL DEFAULT '',
    "sick_leave_days" INTEGER NOT NULL DEFAULT 0,
    "vacation_days" INTEGER NOT NULL DEFAULT 0,
    "sales_target_baht" DOUBLE PRECISION NOT NULL DEFAULT 0,
    CONSTRAINT "user_data_pkey" PRIMARY KEY ("user_id")
);

CREATE UNIQUE INDEX "user_data_username_key" ON "user_data"("username");

CREATE TABLE "job_data" (
    "job_id" SERIAL NOT NULL,
    "profile_id" INTEGER NOT NULL DEFAULT 1,
    "job_no" INTEGER NOT NULL DEFAULT 0,
    "customer_id" INTEGER NOT NULL DEFAULT 0,
    "service_id" VARCHAR(15) NOT NULL DEFAULT '',
    "product_name" VARCHAR(200) NOT NULL DEFAULT '',
    "model" VARCHAR(200) NOT NULL DEFAULT '',
    "brand" VARCHAR(200) NOT NULL DEFAULT '',
    "sn" VARCHAR(100) NOT NULL DEFAULT '',
    "job_amount" INTEGER NOT NULL DEFAULT 0,
    "info" TEXT NOT NULL DEFAULT '',
    "recive_job" DATE NOT NULL,
    "send_job" DATE NOT NULL,
    "job_condition" TEXT NOT NULL DEFAULT '',
    "workgroup_id" INTEGER NOT NULL DEFAULT 0,
    "sale_id" INTEGER NOT NULL DEFAULT 0,
    "engeneer_id" INTEGER NOT NULL DEFAULT 0,
    "job_status" SMALLINT NOT NULL DEFAULT 0,
    "job_po" VARCHAR(50) NOT NULL DEFAULT '',
    "job_quotation" VARCHAR(20) NOT NULL DEFAULT '',
    "job_invoice" VARCHAR(20) NOT NULL DEFAULT '',
    "job_delivery" VARCHAR(20) NOT NULL DEFAULT '',
    "img1" VARCHAR(50) NOT NULL DEFAULT '',
    "img2" VARCHAR(50) NOT NULL DEFAULT '',
    "public" INTEGER NOT NULL DEFAULT 1,
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "job_data_pkey" PRIMARY KEY ("job_id")
);

CREATE INDEX "job_data_job_status_idx" ON "job_data"("job_status");
CREATE INDEX "job_data_sale_id_idx" ON "job_data"("sale_id");
CREATE INDEX "job_data_customer_id_idx" ON "job_data"("customer_id");
CREATE INDEX "job_data_recive_job_idx" ON "job_data"("recive_job");

CREATE TABLE "bill_quota" (
    "quota_id" SERIAL NOT NULL,
    "profile_id" INTEGER NOT NULL DEFAULT 1,
    "job_id" INTEGER NOT NULL DEFAULT 0,
    "unit_price" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "grand_total" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "quota_no" INTEGER NOT NULL DEFAULT 0,
    "quota_to" VARCHAR(200) NOT NULL DEFAULT '',
    "quota_date" DATE NOT NULL,
    "quota_time" TIME NOT NULL DEFAULT '00:00:00',
    "quota_info" TEXT NOT NULL DEFAULT '',
    "bill_id" VARCHAR(20) NOT NULL DEFAULT '',
    "year" VARCHAR(4) NOT NULL DEFAULT '',
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "bill_quota_pkey" PRIMARY KEY ("quota_id")
);

CREATE INDEX "bill_quota_quota_date_idx" ON "bill_quota"("quota_date");
CREATE INDEX "bill_quota_user_id_idx" ON "bill_quota"("user_id");

CREATE TABLE "bill_order" (
    "bo_id" SERIAL NOT NULL,
    "profile_id" INTEGER NOT NULL DEFAULT 1,
    "bo_number" INTEGER NOT NULL DEFAULT 0,
    "job_id" INTEGER NOT NULL DEFAULT 0,
    "bo_no" VARCHAR(200) NOT NULL DEFAULT '',
    "ref_qt" VARCHAR(50) NOT NULL DEFAULT '',
    "ref_po" VARCHAR(50) NOT NULL DEFAULT '',
    "bo_imoney" VARCHAR(200) NOT NULL DEFAULT '',
    "bo_date" DATE NOT NULL,
    "bo_cardit" VARCHAR(50) NOT NULL DEFAULT '',
    "send_date" DATE NOT NULL,
    "audit_status" INTEGER NOT NULL DEFAULT 0,
    "bo_receive" INTEGER NOT NULL DEFAULT 0,
    "market" INTEGER NOT NULL DEFAULT 0,
    "grandtotal" VARCHAR(50) NOT NULL DEFAULT '',
    "bo_info" TEXT NOT NULL DEFAULT '',
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "bill_order_pkey" PRIMARY KEY ("bo_id")
);

CREATE INDEX "bill_order_bo_date_idx" ON "bill_order"("bo_date");

CREATE TABLE "bill_invoice" (
    "inv_id" SERIAL NOT NULL,
    "profile_id" INTEGER NOT NULL DEFAULT 1,
    "job_id" INTEGER NOT NULL DEFAULT 0,
    "inv_number" INTEGER NOT NULL DEFAULT 0,
    "inv_no" VARCHAR(20) NOT NULL DEFAULT '',
    "inv_date" DATE NOT NULL,
    "inv_info" TEXT NOT NULL DEFAULT '',
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "bill_invoice_pkey" PRIMARY KEY ("inv_id")
);

CREATE TABLE "pr_data" (
    "pr_id" SERIAL NOT NULL,
    "profile_id" INTEGER NOT NULL DEFAULT 1,
    "job_id" INTEGER NOT NULL DEFAULT 0,
    "pr_no" INTEGER NOT NULL DEFAULT 0,
    "pr_code" VARCHAR(20) NOT NULL DEFAULT '',
    "pr_date" DATE NOT NULL,
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "pr_data_pkey" PRIMARY KEY ("pr_id")
);

CREATE TABLE "receive_order" (
    "ro_id" SERIAL NOT NULL,
    "profile_id" INTEGER NOT NULL DEFAULT 1,
    "bo_id" INTEGER NOT NULL DEFAULT 0,
    "ro_number" INTEGER NOT NULL DEFAULT 0,
    "job_id" INTEGER NOT NULL DEFAULT 0,
    "ro_no" VARCHAR(20) NOT NULL DEFAULT '',
    "ro_date" DATE NOT NULL,
    "ro_po" VARCHAR(100) NOT NULL DEFAULT '',
    "ro_tax" VARCHAR(20) NOT NULL DEFAULT '',
    "ro_ref" VARCHAR(100) NOT NULL DEFAULT '',
    "ro_credit" VARCHAR(100) NOT NULL DEFAULT '',
    "end_date" DATE NOT NULL,
    "advance_payment" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "tax" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "ro_info" TEXT NOT NULL DEFAULT '',
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "receive_order_pkey" PRIMARY KEY ("ro_id")
);

CREATE TABLE "rfq" (
    "rfq_id" SERIAL NOT NULL,
    "rfq_confirm" INTEGER NOT NULL DEFAULT 0,
    "rfq_no" VARCHAR(20) NOT NULL DEFAULT '',
    "rfq_date" DATE NOT NULL,
    "job_id" INTEGER NOT NULL DEFAULT 0,
    "profile_id" INTEGER NOT NULL DEFAULT 1,
    "modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "rfq_pkey" PRIMARY KEY ("rfq_id")
);

CREATE TABLE "sparepart" (
    "part_id" SERIAL NOT NULL,
    "job_id" INTEGER NOT NULL DEFAULT 0,
    "sp_img" VARCHAR(200) NOT NULL DEFAULT '',
    "part_no" VARCHAR(100) NOT NULL DEFAULT '',
    "part_detail" TEXT NOT NULL DEFAULT '',
    "case_stype" VARCHAR(200) NOT NULL DEFAULT '',
    "part_num" INTEGER NOT NULL DEFAULT 0,
    "part_info" TEXT NOT NULL DEFAULT '',
    "rfq_id" INTEGER NOT NULL DEFAULT 0,
    "store_one" INTEGER NOT NULL DEFAULT 0,
    "price1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "vat1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "store_two" INTEGER NOT NULL DEFAULT 0,
    "price2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "vat2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "store_three" INTEGER NOT NULL DEFAULT 0,
    "price3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "vat3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "store_buy" INTEGER NOT NULL DEFAULT 0,
    "total" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "descount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "unit" VARCHAR(50) NOT NULL DEFAULT '',
    "part_status" INTEGER NOT NULL DEFAULT 0,
    "receive_status" INTEGER NOT NULL DEFAULT 0,
    "user_id" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "sparepart_pkey" PRIMARY KEY ("part_id")
);

-- Seed: workstatus / workgroup / user_group (ขั้นตอนงาน + กลุ่มงาน + กลุ่มผู้ใช้)
INSERT INTO "workstatus" ("ws_id", "ws_name", "info", "list", "public", "user_id") VALUES
 (1, 'N01. รับงาน', 'บันทึกข้อมูลงานที่รับเข้าบริษัท', 1, 1, 2),
 (2, 'N02. ออกแบบตรวจเช็ค', 'หัวหน้าช่างเลือกผู้รับผิดชอบงานนั้น(เลือกช่าง) และช่างที่ได้รับมอบหมายดำเนินการตรวจเช็ค, ออกแบบ, ผลิต', 2, 1, 2),
 (3, 'N03. ขอข้อมูลเพิ่มเติมฝ่ายขาย', 'ทางช่างขอข้อมูลเพิ่มเติมจาก SALE ในงานที่อาจจะติดปัญหา', 3, 1, 2),
 (4, 'N04. หาราคาอะไหล่', 'ทางช่างขออะไหล่ กรอกข้อมูลครบถ้วน (หาราคาอะไหล่)', 4, 1, 2),
 (5, 'N05. หาราคาเสร็จสิ้น', 'หาราคาอะไหล่ครบถ้วนทุกรายการเรียบร้อย', 5, 1, 2),
 (6, 'N06. เสนอราคา', 'จัดทำเอกสารใบเสนอราคาให้ทางลูกค้าแล้ว', 6, 1, 0),
 (7, 'N07. รอ PO ลูกค้า', 'เสนอราคาแล้ว รอลูกค้าพิจารณาว่าต้องการซ่อมหรือไม่', 7, 1, 0),
 (8, 'N08. PO มาแล้ว', 'ลูกค้าอนุมัติซ่อมแล้ว', 8, 1, 0),
 (9, 'N09. เปิด PR ', 'ขออนุมัติซื้ออะไหล่ ( เอกสาร )', 9, 1, 0),
 (10, 'N10. เปิด PO จัดซื้อ', 'ได้รับการอนุมัติ PR แล้ว เปิด PO สั่งซื้อสินค้า', 10, 1, 0),
 (11, 'N11. รอบัญชีชำระเงิน', 'ใส่เลข PO I-money เรียบร้อยแล้ว (รอทางบัญชีทำขั้นตอนการจ่ายเงิน เงินสด, เช็ค, โอน, เครดิต)', 11, 1, 0),
 (12, 'N12. รอรับของ(อะไหล่)', 'บัญชีชำระเงินเรียบร้อยแล้ว สั่งของกับ Supplier เรียบร้อย', 12, 1, 0),
 (13, 'N13. ของมาแล้ว ', 'สินค้าที่สั่งกับ Supplier ดำเนินการส่งของแล้ว (Stroe ทำใบรับสินค้า)', 13, 1, 0),
 (14, 'N14. ดำเนินการผลิต(อะไหล่มาครบ)', 'ช่างได้รับอะไหล่เรียบร้อยแล้ว', 14, 1, 0),
 (15, 'N15. ซ่อมเสร็จแล้ว', 'ช่างดำเนินการซ่อม ผลิต เรียบร้อย', 15, 1, 0),
 (16, 'N16. ส่งของเทส', 'ช่างซ่อมเสร็จ Sale นำงานไปเทสให้ลูกค้า (ต้องมีเอกสารใบส่งของอ้างอิง)', 16, 1, 0),
 (17, 'N17. รอเก็บเงิน', 'ใส่เลขที่เอกสารวางบิลและเลขที่เอกสารใบกำกับภาษี', 17, 1, 0),
 (18, 'N18. ปิดงาน', 'ใส่เลขที่เอกสารใบเสร็จรับเงิน (จบงาน)', 18, 1, 0),
 (19, 'N19. ยกเลิก-คืนงาน', 'ลูกค้าไม่ซ่อมหรือถึงกำหนดคืนงาน (ต้องมีเลขที่เอกสารใบส่งของคืนอ้างอิง)', 19, 1, 0),
 (20, 'เครม', 'ไม่ผ่าน', 20, 1, 0);

INSERT INTO "workgroup" ("wg_id", "wg_name", "info", "list", "public", "user_id") VALUES
 (3, 'งานขาย', 'ซื้อสินค้าและขายออกไป', 1, 1, 0),
 (7, 'งานซ่อม', 'งานซ่อมทุกชนิด', 3, 1, 2),
 (8, 'งานโปรเจค', 'COPY และ วิจัย', 4, 1, 19),
 (9, 'งานผลิต', 'ผลิตสินค้า', 5, 1, 19),
 (10, 'งานออกแบบ', 'เขียนแบบ', 6, 1, 0),
 (11, 'งานสโตร์', 'หาอะไหล่เข้าสโตร์ พร้อมขาย', 7, 1, 0);

INSERT INTO "user_group" ("group_id", "group_tid", "group_name", "file", "info", "admin", "public", "datetime") VALUES
 (1, 1, 'ผู้ดูแลระบบ/Admin', 'Human-Resource-Management.jpg', 'ผู้ดูแลระบบสูงสุด', 1, 1, ''),
 (2, 1, 'พนักงานขาย', 'Human-Resource-Management.jpg', 'พนักงานขายสินค้า', 1, 1, ''),
 (9, 0, 'จัดหา', '', 'หาอะไหล่ที่สโตร์ไม่มี', 0, 1, ''),
 (10, 0, 'ผู้จัดการบัญชี/การเงิน', '', 'จัดการดูแลรับจ่าย', 0, 1, ''),
 (5, 0, 'ฝ่ายผลิต', '', 'ช่าง', 0, 1, ''),
 (6, 0, 'สโตร์', '', 'ผู้ดูแลคลังสินค้า', 0, 1, ''),
 (7, 0, 'Support Sale', '', 'ซัพพลอตพนักงานขาย', 0, 1, ''),
 (8, 0, 'ผู้จัดการฝ่ายผลิต', '', 'ผู้ที่สามารถเลือกผู้รับผิดชอบทีมช่างได้คนเดียวเท่านั้น', 0, 1, ''),
 (11, 0, 'บัญชี/การเงิน', '', 'ดูแลรับจ่าย', 0, 1, ''),
 (13, 0, 'ผู้จัดการบริษัท', '', 'ดูแลทั้งหมด', 0, 1, ''),
 (14, 0, 'ผู้จัดการฝ่ายบุคคล', '', '', 0, 1, ''),
 (15, 0, 'ฝ่ายบุคคล', '', '', 0, 1, ''),
 (17, 0, 'ผู้จัดการฝ่ายขาย', '', 'ดูแลทีมขาย', 0, 1, ''),
 (18, 0, 'บริการ', '', 'ดูแลบริษัท', 0, 1, ''),
 (20, 0, 'หัวหน้าทีมซ่อม', '', 'หัวหน้าทีมซ่อม', 0, 1, ''),
 (21, 0, 'หัวหน้าทีม ASL', '', 'หัวหน้าทีมซ่อม ASL', 0, 1, ''),
 (22, 0, 'หัวหน้าทีม ประกอบ', '', 'หัวหน้าทีมประกอบงาน', 0, 1, '');
